# fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # https://github.com/pre-commit/pre-commit-hooks/blob/main/.pre-commit-hooks.yaml
      # - id: check-added-large-files
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-illegal-windows-names
      - id: check-json
      # - id: check-shebang-scripts-are-executable
      # - id: pretty-format-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      # - id: detect-aws-credentials
      - id: detect-private-key
      # - id: double-quote-string-fixer
      # - id: end-of-file-fixer
      - id: file-contents-sorter
      - id: fix-byte-order-marker
      # - id: fix-encoding-pragma
      - id: forbid-new-submodules
      - id: forbid-submodules
      - id: mixed-line-ending
      # - id: name-tests-test
      - id: no-commit-to-branch
      # - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace

  # - repo: https://github.com/pycqa/isort
  #   rev: 6.0.0
  #   hooks:
  #     - id: isort

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.12

  - repo: local
    hooks:
      - id: requirements
        name: export requirements
        entry: export_requirements.sh
        language: script
        pass_filenames: false
        verbose: true
        stages: [pre-commit]
      # - id: swagger # covert v3 to v2 by api-spec-converter
      #   name: export swagger
      #   entry: export_swagger.sh
      #   language: script
      #   pass_filenames: false
      #   verbose: true
      #   stages: [pre-commit]
      - id: pylint
        name: pylint
        entry: uv run coverage run --source=src -m pytest -v --pylint --pylint-rcfile pylintrc -m pylint .
        language: system
        pass_filenames: false
        stages: [pre-commit]
      # - id: pytest
      #   name: pytest
      #   entry: uv run coverage run --source=src -m pytest -v tests/unit/ tests/auto/unit_gpt/
      #   language: system
      #   pass_filenames: false
      #   stages: [pre-commit]
      # - id: behave
      #   name: behave
      #   entry: env PYTHONPATH=./src/ SLOW_TEST_LOCAL=1 pipenv run behave --format=pretty --logging-clear-handlers -v tests/integration/
      #   language: system
      #   pass_filenames: false
      #   stages: [pre-commit]
